author_email: musyoki.brian@tralahtek.com
author_name: Tralah M Brian
author_username: TralahM
console_scripts: ''
install_requires: ''
language: ''
licence: MIT
package_name: ''
program_description: ''
program_name: ''
readthedocs: true
repo_name: TralahM
version: '0.1'
